### ISSUE TITLE
dd error when building box

### ISSUE THREAD

**Issue by thomas-scrace** [django/django-box#13]
Using b7765b6 I hit the same problem as https://github.com/django/django-box/issues/12 and am trying to build a box using

`VAGRANT_VAGRANTFILE=Vagrantfile-build vagrant up`

Everything goes well all the way through ansible provisioning, but I then get:

```
PLAY RECAP *********************************************************************
default                    : ok=56   changed=51   unreachable=0    failed=0

==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mesg: ttyname failed: Inappropriate ioctl for device
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: W
==> default: :
==> default: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list:1 and /etc/apt/sources.list.d/google-chrome.list:3
==> default: W
==> default: :
==> default: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list:1 and /etc/apt/sources.list.d/google-chrome.list:3
==> default: W
==> default: :
==> default: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list:1 and /etc/apt/sources.list.d/google-chrome.list:3
==> default: W
==> default: :
==> default: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list:1 and /etc/apt/sources.list.d/google-chrome.list:3
==> default: W
==> default: :
==> default: Target Translations (main/i18n/Translation-en_GB) is configured multiple times in /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list:1 and /etc/apt/sources.list.d/google-chrome.list:3
==> default: 35165107+0 records in
==> default: 35165107+0 records out
==> default: 36009069568 bytes (36 GB, 34 GiB) copied, 93.241 s, 386 MB/s
==> default: 404196+0 records in
==> default: 404196+0 records out
==> default: 413896704 bytes (414 MB, 395 MiB) copied, 1.48731 s, 278 MB/s
==> default: dd:
==> default: writing to '/dev/dm-1'
==> default: : No space left on device
==> default: 1048577+0 records in
==> default: 1048576+0 records out
==> default: 536870912 bytes (537 MB, 512 MiB) copied, 14.2287 s, 37.7 MB/s
==> default: Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
==> default: no label, UUID=393fe33a-8094-49f4-8f28-e69ff6ff9a93
```

This is using Vagrant 1.8.5 and VirtualBox 5.1.4 on OS X 10.11.6.

My django repo is checked out at 14879ac.

**Comment by thomas-scrace** [comment]
I should note that I can ssh into the box fine, and some test aliases (e.g. `runtests-docs`) work, but many don't (e.g. `runtests27-mysql`) and fail with errors like:

`ERROR:   py27-mysql: could not install deps [-rtests/requirements/py2.txt, -rtests/requirements/mysql.txt]; v = InvocationError('/django/.tox/py27-mysql/bin/pip install -rtests/requirements/py2.txt -rtests/requirements/mysql.txt (see /django/.tox/py27-mysql/log/py27-mysql-1.log)', 1)`

**Comment by thomas-scrace** [comment]
I think these two issues are actually unrelated, so apologies for mixing them up.

All the test aliases I have tried so far now work after having done:

`sudo apt-get install zlib1g-dev`

**Comment by thomas-scrace** [comment]
Which I really find hard to understand, since the python ansible role is supposed to install this package, and indeed claims to have done so:

`TASK [python : install extra packages required by Python dependencies] *********
changed: [default] => (item=[u'libffi-dev', u'libjpeg-dev', u'zlib1g-dev', u'git'])`

I'm going to try this all again from scratch.

**Comment by thomas-scrace** [comment]
Odd. This time the tests ran fine without installing anything extra. Sorry for the noise.

Original dd problem is consistent, but I'm still left with a working test environment.

**Comment by jarshwah** [comment]
@thomas-scrace thanks for slimming that down! Odd that zlib1g wasn't properly installed, hopefully that's a one off. The idea is that the build file shouldn't be the interface that people use. To that end, I'm going to try and get the compiled box uploaded today.

As far as the `dd` problem goes though, it's supposed to error at some point. The entire point of it is to fill up the disk with empty data so that it can be compressed better when generating the .box image. When it fills up you get the error code, but that's a good thing. Again though, once the compiled box is uploaded most users shouldn't ever see that happen.

Unless I'm missing the real issue with the `dd` step?

**Comment by thomas-scrace** [comment]
Ah! That makes sense. Sorry.

Definitely agree that the compiled box thing is a good idea.
