### ISSUE TITLE
Some more guidance about testing for beginners in README.md

### ISSUE THREAD

**Issue by olivierdalang** [django/django-box#17]
Hi,

It's great to have django-box, as it makes it easy to run test for new contributors. This only thing I find missing is a bit more guidance aimed at beginners. Some of it is covered on https://docs.djangoproject.com/en/1.10/topics/testing/overview/ but it doesn't seem to fully match with what's possible in django-box with the `runtestsXX-xxx` shortcuts.
- What to do when a test fails ? How to debug failing tests ? Naive approaches such as using print statements, raising exceptions don't output anything usable in the console, using pdb also doesn't seem possible. Also it's not clear whether and how it's possible to use manage.py to run the dev server and test live using the shell or the browser.
- Is it possible to speed up testing ? By default, all the tests are run, which is very long. It is possible to restrict to one particular module using eg. `runtests35-mysql admin_views` (`runtests35-mysql admin_views.UserAdminTest` or `runtests35-mysql admin_views.UserAdminTest.test_user_fk_change_popup` don't seem to work though), but this still takes more than 2 minutes to setup, making code/test iterations quite slow. Is it possible to avoid deletion/recreation of the database each time (which seem to be the most time-consuming task) ?
- Is it possible to run all test at once, ideally exactly as done by Jenkins, so to make sure a commit passes all tests before making a PR ? By default, it seems the output of `runtestsXX-xxxx` goes to the console, but not to the .tox directory, so that it's hard to get a clean overview of what happened.

Thanks a lot for the box already, I think it's a big step towards getting more and better contributions to django ! (at least for me)

**Comment by timgraham** [comment]
I guess it's not clear that much of the documentation at https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/ is relevant.

**Comment by olivierdalang** [comment]
Indeed that helps a lot.

It seems selenium tests are skipped, is this normal ? How can I include them ? (I try to work on PR https://github.com/django/django/pull/6818 which include a selenium test).

**Comment by timgraham** [comment]
The linked document has a section "Running the Selenium tests".

**Comment by olivierdalang** [comment]
Oops I missed it, I was expecting tox to run all the tests, just as jenkins does on github.

Still, I don't think the command `./runtests.py --selenium=firefox,chrome` can work out of the box on the django-box.

I tried `runtests35-postgres --selenium=firefox admin_inlines` I get `

```
ERROR: setUpClass (admin_inlines.tests.SeleniumTests)
(...)
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
```

Am I doing it wrong or are selenium tests not supported on django-box yet ?

**Comment by timgraham** [comment]
I guess if you can't run `firefox` from the command line, then it's not installed.

**Comment by jarshwah** [comment]
That's correct, only the chrome driver is currently installed into the vagrant image. I think linking to the testing docs Tim provided in the README might be a good way to go. As well as offering some examples of running the tests from within vagrant (using keepdb and selenium flags, targeting specific test packages, etc).
