### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

### ISSUE THREAD

**Issue by abhimanusharma** [django/django-box#36]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'djangoproject/django-box-2.0' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'djangoproject/django-box-2.0'
    default: URL: https://vagrantcloud.com/djangoproject/django-box-2.0
==> default: Adding box 'djangoproject/django-box-2.0' (v2.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/djangoproject/boxes/django-box-2.0/versions/2.0.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

**Comment by ramiro** [comment]
This is happening when Vangrant attempts to download the box from Hashicorp Atlas.

A Google search shows this is a non-django-box-specific problem involving the host system and/or Vagrant.

Please try to find a solution using Vagrant support channels. It could be your Vagrant instalation is an old version, badly installed or that your OS SSL libraries need updating.

You ca try if downloading the `hashicorp/precise64` box from Atlas as described in the Vagrant Getting Started document suffers from the same problem: https://www.vagrantup.com/intro/getting-started/index.html

If you find this is actually a problem with django-box then please reopen this issue.
